<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Destination;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Dubai Dreamscape',
                'slug' => 'dubai-dreamscape',
                'description' => 'Discover the glamour of Dubai with skyscraper views, desert safaris, and luxurious experiences.',
                'country' => 'United Arab Emirates',
                'city' => 'Dubai',
                'type' => 'city',
                'featured_image' => 'https://images.pexels.com/photos/325193/pexels-photo-325193.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'Visit the Burj Khalifa, shop at Dubai Mall, and enjoy a desert safari.',
                'best_time_to_visit' => 'October to April',
                'nearest_airport' => 'Dubai International Airport (DXB)',
                'local_transport' => 'Metro, taxis, rental cars. The Dubai Metro connects major areas. Taxis are affordable and readily available.',
                'must_see_attractions' => 'Burj Khalifa, Dubai Mall, Dubai Fountain, Palm Jumeirah, Desert Safari, Souk markets',
                'safety_tips' => 'Dubai is very safe. Dress modestly in public places. Traffic can be intense; use metro or taxis.',
                'history_culture' => 'Dubai transformed from a small fishing village to a global hub in just 50 years. Emirati culture blends traditional values with ultra-modern innovation.',
                'entry_fees' => 'Burj Khalifa: AED 500 (~$136), Dubai Mall: Free, Most beaches: Free',
                'photo_gallery_1' => 'https://images.pexels.com/photos/325193/pexels-photo-325193.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/1439405/pexels-photo-1439405.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/1024975/pexels-photo-1024975.jpeg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => 25.2048,
                'longitude' => 55.2708,
            ],
            [
                'name' => 'Bali Bliss Retreat',
                'slug' => 'bali-bliss-retreat',
                'description' => 'Immerse yourself in tropical serenity, terraced rice fields, and Balinese cultural wonders.',
                'country' => 'Indonesia',
                'city' => 'Bali',
                'type' => 'island',
                'featured_image' => 'https://images.pexels.com/photos/248797/pexels-photo-248797.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'Explore Ubud, relax on the beaches, and visit ancient temples.',
                'best_time_to_visit' => 'April to October (dry season)',
                'nearest_airport' => 'Ngurah Rai International Airport (DPS)',
                'local_transport' => 'Scooters, taxis, ride-sharing apps (Gojek, Grab). Scooter rentals are cheap and popular.',
                'must_see_attractions' => 'Ubud Rice Terraces, Tanah Lot Temple, Tirta Empul Water Temple, Bali Swing, Monkey Forest, Beaches of Seminyak',
                'safety_tips' => 'Generally safe but watch valuables in crowded areas. Avoid traveling at night on unfamiliar roads. Traffic is chaotic; be cautious.',
                'history_culture' => 'Bali is the heart of Indonesian Hinduism. Traditional ceremonies, intricate carvings, and spiritual practices define Balinese culture. The island has a rich artistic heritage.',
                'entry_fees' => 'Temples: ~50,000-150,000 IDR (~$3-10), Monkey Forest: 150,000 IDR, Bali Swing: varies 100,000-200,000 IDR',
                'photo_gallery_1' => 'https://images.pexels.com/photos/248797/pexels-photo-248797.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/1909625/pexels-photo-1909625.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/1450354/pexels-photo-1450354.jpeg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => -8.3405,
                'longitude' => 115.0920,
            ],
            [
                'name' => 'Mauritius Marvel',
                'slug' => 'mauritius-marvel',
                'description' => 'White-sand beaches, turquoise waters, and romantic sunsets for the ultimate island escape.',
                'country' => 'Mauritius',
                'city' => 'Port Louis',
                'type' => 'island',
                'featured_image' => 'https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'Snorkel in Blue Bay, hike Le Morne, and enjoy local cuisine.',
                'best_time_to_visit' => 'May to December (cooler, dry season)',
                'nearest_airport' => 'Sir Seewoosagur Ramgoolam International Airport (MRU)',
                'local_transport' => 'Buses, rental cars, taxis. Buses are affordable and cover most areas. Taxis are available but negotiate fares.',
                'must_see_attractions' => 'Blue Bay Beach, Le Morne Brabant, Chamarel Waterfall, Pamplemousses Botanical Garden, Port Louis Waterfront, Ile aux Cerfs',
                'safety_tips' => 'Safe destination. Be cautious in Port Louis at night. Use registered taxis or ride-sharing apps. Water is safe to drink.',
                'history_culture' => 'Mauritius is a multicultural island with Hindu, Muslim, Christian, and other communities. Former French and British colony, it gained independence in 1968. Sugar industry shaped its history.',
                'entry_fees' => 'Blue Bay Beach: Free, Le Morne hiking: Free, Pamplemousses Garden: ~600 MUR (~$13)',
                'photo_gallery_1' => 'https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/1444814/pexels-photo-1444814.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/1000363/pexels-photo-1000363.jpeg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => -20.3484,
                'longitude' => 57.5522,
            ],
            [
                'name' => 'USA Explorer',
                'slug' => 'usa-explorer',
                'description' => 'From New York skylines to canyon vistas, build the ultimate American road trip.',
                'country' => 'United States',
                'city' => 'New York',
                'type' => 'city',
                'featured_image' => 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'See the Statue of Liberty, visit Times Square, and drive Route 66.',
                'best_time_to_visit' => 'September to November, March to May',
                'nearest_airport' => 'JFK International, LaGuardia, Newark Liberty',
                'local_transport' => 'Subway, buses, taxis, Uber/Lyft. NYC has the best public transit. For road trips, rent a car.',
                'must_see_attractions' => 'Statue of Liberty, Empire State Building, Central Park, Times Square, Grand Central Terminal, Brooklyn Bridge, 9/11 Memorial',
                'safety_tips' => 'NYC is generally safe. Avoid empty streets late at night. Use official taxis or ride-sharing apps. Keep valuables secure.',
                'history_culture' => 'NYC is the cultural melting pot of America. Home to immigrants from around the world, it shaped American culture, finance, and arts. Broadway, museums, and diverse neighborhoods reflect global influence.',
                'entry_fees' => 'Statue of Liberty: $24, Empire State Building: $39, Most museums: $20-28',
                'photo_gallery_1' => 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/1105818/pexels-photo-1105818.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/839359/pexels-photo-839359.jpeg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
            ],
            [
                'name' => 'Miami Sun & Sea Escape',
                'slug' => 'miami-sun-sea-escape',
                'description' => 'Vibrant nightlife, Art Deco charm, and beach days soaked in sunshine on Miami Beach.',
                'country' => 'United States',
                'city' => 'Miami',
                'type' => 'beach',
                'featured_image' => 'https://images.pexels.com/photos/208701/pexels-photo-208701.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'Relax on South Beach, explore Little Havana, and enjoy the nightlife.',
                'best_time_to_visit' => 'November to April',
                'nearest_airport' => 'Miami International Airport (MIA)',
                'local_transport' => 'Rental cars recommended. Metromover is free within downtown. Taxis, Uber/Lyft available.',
                'must_see_attractions' => 'South Beach, Art Deco Historic District, Little Havana, Wynwood Walls, Vizcaya Museum, Everglades National Park',
                'safety_tips' => 'Miami is mostly safe but avoid certain neighborhoods at night. Use official transportation. Beach safety: watch for rip currents.',
                'history_culture' => 'Miami became a major hub after the Cuban Revolution (1959). Latin American influence, especially Cuban, defines Miami culture. Art Deco architecture, vibrant street art, and diverse food scene.',
                'entry_fees' => 'South Beach: Free, Vizcaya Museum: $25, Everglades tours: $30-50',
                'photo_gallery_1' => 'https://images.pexels.com/photos/208701/pexels-photo-208701.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/681494/pexels-photo-681494.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/1682519/pexels-photo-1682519.jpeg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
            ],
            [
                'name' => 'Agra Heritage Journey',
                'slug' => 'agra-heritage-journey',
                'description' => 'Witness the Taj Mahal at dawn and wander through centuries of Mughal architecture.',
                'country' => 'India',
                'city' => 'Agra',
                'type' => 'city',
                'featured_image' => 'https://images.pexels.com/photos/460376/pexels-photo-460376.jpeg?auto=compress&cs=tinysrgb&w=800',
                'travel_tips' => 'Visit the Taj Mahal, Agra Fort, and Fatehpur Sikri.',
                'best_time_to_visit' => 'October to March',
                'nearest_airport' => 'Indira Gandhi International Airport (DEL) - Delhi, 206 km away',
                'local_transport' => 'Taxis, auto-rickshaws, or guides. Trains connect Agra to other Indian cities. Scooters for local exploration.',
                'must_see_attractions' => 'Taj Mahal, Agra Fort, Fatehpur Sikri, Mehtab Bagh, Taj Mahal at Sunrise, Etmad-ud-Daulah',
                'safety_tips' => 'Generally safe. Beware of unofficial guides and overpricing. Bargain at markets. Stay hydrated in summer heat (April-May 45°C+).',
                'history_culture' => 'Agra was the capital of the Mughal Empire. The Taj Mahal was built by Emperor Shah Jahan for his wife Mumtaz Mahal (1632-1653). It\'s a symbol of eternal love and Islamic architecture.',
                'entry_fees' => 'Taj Mahal: ₹250 Indian / $40 foreign, Agra Fort: ₹300/$25, Fatehpur Sikri: ₹290/$20',
                'photo_gallery_1' => 'https://images.pexels.com/photos/460376/pexels-photo-460376.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_2' => 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800',
                'photo_gallery_3' => 'https://images.pexels.com/photos/6282/taj-mahal-agra-mughal-monument.jpg?auto=compress&cs=tinysrgb&w=800',
                'latitude' => 27.1767,
                'longitude' => 78.0081,
            ],
        ];
        foreach ($destinations as $data) {
            \App\Models\Destination::updateOrCreate([
                'slug' => $data['slug']
            ], $data);
        }
    }
}

